title: Vanessa Núñez
logo: /Images/logo.png
description: I’m a Data Analyst with experience in machine learning and academic research. I have a strong analytical mind and a passion for storytelling. As an empathetic communicator, I translate complex information into creative and insightful presentations to engage a diverse audience effectively. I have worked for over six years developing a voice assistant that helps millions of customers daily. Now, I am eager to use my expertise to deep dive analyses to provide clear observations so that people leaders can make more informed decisions.
  <div><a href="https://www.linkedin.com/in/vanessa-nunez-penas" target="_blank">View My LinkedIn Profile</a></div>
  <div><a href="https://github.com/vanessanunezp" target="_blank">View My GitHub Repository</a></div>
  <div><a href="https://public.tableau.com/app/profile/vanessa.nunez.penas/vizzes" target="_blank">View My Tableau Public</a></div>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
