title: Vanessa Núñez
logo: /Images/VanessaNunez.jpg
description: I’m a Data Analyst with experience in machine learning and academic research. I have a strong analytical mind and a passion for storytelling. As an empathetic communicator, I translate complex information into creative and insightful presentations to engage a diverse audience effectively. I have worked for over six years developing a voice assistant that helps millions of customers daily. One of my proudest achievements was to solve biases and constraints in our projects with constructive feedback. Now, I am eager to use my expertise to deep dive analyses to provide clear observations so that people leaders can make more informed decisions.
  <br><br>
  <a href="https://www.linkedin.com/in/vanessa-nunez-penas">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://github.com/VaNuPe">View My GitHub Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/vanessa.nunez.penas/vizzes">View My Tableau Public Profile</a>
  
theme: jekyll-theme-minimal
