title: Vanessa Núñez
logo: /Images/logo.png
description: I’m a Data Analyst with experience in machine learning and academic research. Engaging communicator skilled in crafting stories to deliver powerful outcomes for diverse audiences. Enjoy working in a team, being in contact with clients, and overcoming obstacles and challenges contributing to effective decision-making. 
  <div><a href="https://www.linkedin.com/in/vanessa-nunez-penas" target="_blank">View My LinkedIn Profile</a></div>
  <div><a href="https://github.com/vanessanunezp" target="_blank">View My GitHub Repository</a></div>
  <div><a href="https://public.tableau.com/app/profile/vanessa.nunez.penas/vizzes" target="_blank">View My Tableau Public</a></div>
  
theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
